/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMandalaRenderer,
  IMandalaRendererInterface,
} from "../../../contracts/HashJingNFT.sol/IMandalaRenderer";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
    ],
    name: "svg",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMandalaRenderer__factory {
  static readonly abi = _abi;
  static createInterface(): IMandalaRendererInterface {
    return new Interface(_abi) as IMandalaRendererInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMandalaRenderer {
    return new Contract(address, _abi, runner) as unknown as IMandalaRenderer;
  }
}
